### PR TITLE
ENH: added laterality modifier

### PR DESCRIPTION
**Pull request by deepakri201**
@fedorov -- I have added the use of the laterality modifier to the quantitative measurements query.

### CODE REVIEW

**Comment by fedorov** [comment]
@deepakri201 @vkt1414 I discussed this with @bcli4d, and since this query just adds a new column and does not remove anything, we could update v18 to include the updated content.

However, we should be very sure we are not missing anything else. Let's for now use a table that is non-public and spend more time analyzing the data. Once the analysis is done and we know there will be no additional modifications, we can propagate this to the release. Sounds good?

**Comment by deepakri201** [comment]
@fedorov -- That sounds good to me!

**Comment by vkt1414** [comment]
same with me.

**Review by fedorov — CHANGES_REQUESTED** [review]
@deepakri201 I missed this earlier - please add the new item schema to https://github.com/ImagingDataCommons/etl_flow/blob/master/bq/generate_tables_and_views/derived_tables/BQ_Table_Building/derived_data_views/schema/quantitative_measurements.json.

**Comment by deepakri201** [comment]
@fedorov I added the lateralityModifier to the schema

**Comment by bcli4d** [comment]
@deepakri201, @fedorov, I've regenerated dicom_metadata_curated_series_level, dicom_metadata_curated_series_level_view, quantitative_measurements and quantitative_measurements_view in idc-dev-etl.idc_v18_pub and idc-pdp-staging.idc_v18. I will push to the public BQ dataset after you've verified that they are good.

**Comment by deepakri201** [comment]
Hi @bcli4d, 

I apologize for the delay, I missed this. The quantitative_measurements table looks good to me, thanks!

**Comment by vkt1414** [comment]
@bcli4d sorry for pushing on this at the last moment. We need this to be fixed and make resulting parquet files available on aws before tomorrow. Thank you!

**Comment by bcli4d** [comment]
@vkt1414 Done. Please verify and let me know if there are any issues (direct email wouldbe best)

**Comment by vkt1414** [comment]
I do see the Laterality attribute now. Thank you!

**Comment by bcli4d** [comment]
👍

**Comment by fedorov** [comment]
@bcli4d @vkt1414  lateralityModifier does show up in `idc_v18`, but I do not see it in `idc_current`.

**Comment by bcli4d** [comment]
@fedorov, @vkt1414  bigquery-public-data.idc_current  views have been updated. Please verify.

**Pull request merged**
