### PR TITLE
added embedding, tissue fixative and staining codes

### PR DESCRIPTION
**Pull request by fedorov**

### CODE REVIEW

**Comment by fedorov** [comment]
@DanielaSchacherer following up on the discussion earlier today.

@dclunie as I thought, `ObjectiveLensPower` is already included in the query. Further, it is also included (in a very obscure way, definitely) in the portal.

image

**Comment by DanielaSchacherer** [comment]
@fedorov If I understand correctly you select any of the values present in the instances for the series for ObjectiveLensPower?

**Comment by bcli4d** [comment]
What is the status of this PR? There still seems to be some uncertainty.

**Comment by fedorov** [comment]
>  If I understand correctly you select any of the values present in the instances for the series for ObjectiveLensPower?

@DanielaSchacherer yes.

That part did not change since the times we together looked at this query when it was first introduced.

**Review by DanielaSchacherer — APPROVED** [review]
Sorry, I missed that this one is still open. I do not have any concerns.

**Pull request merged**
